### ISSUE TITLE
sprint2 작업 분할 관련

### ISSUE THREAD

**Issue by crusaider0614** [swsnu/swpp17-team11#2]
제가 백앤드 테스트를 하도록 하겠습니다.

홈페이지, 홈페이지 생성 관련 Unit Test를 누가 할지 정해주세요. 스타일링은 Bootstrap 쓰기로 했으니 수요일에 다 같이 공부해서 마무리하도록 합니다.

**Comment by crusaider0614** [comment]
그리고 Back의 View도 있어요.

**Comment by lkys221** [comment]
전 Backend view.py 할께요

**Comment by yzoo1008** [comment]
Then I'll do frontend homepage
